export const ProductsSelled = [
    {
      productId:"cod_80001"      
    },
    {
      productId:"cod_60001"      
    },
    {
      productId:"cod_70004"      
    },
    {
      productId:"cod_20012"      
    },
    {
      productId:"cod_11016"      
    },
    {
      productId:"cod_16031"      
    }
  ];