export const ProductsSelled = [
    {
      productId:"cod_80001"      
    },
    {
      productId:"cod_60001"      
    },
    {
      productId:"cod_70004"      
    },
    {
      productId:"cod_20014"      
    },
    {
      productId:"cod_10023"      
    },
    {
      productId:"cod_19007"      
    }
  ];